name = "sms-llm"
main = "src/index.ts"
compatibility_date = "2023-11-21"

[ai]
binding = "AI" # i.e. available in your Worker on env.AI

[vars]
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9" # don't store secrets in vars, use a secret store instead