name = "cloudflare-workers-ai"
main = "src/index.ts"
compatibility_date = "2023-11-21"

[ai]
binding = "AI" # i.e. available in your Worker on env.AI

[vars]
API_KEY = "secret" # don't store secrets in vars, use a secret store instead